// Package static Code generated by swaggo/swag. DO NOT EDIT
package static

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@moh-central.net"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/device": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Init Device Auth",
                "parameters": [
                    {
                        "description": "Auth Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeviceAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token Info",
                        "schema": {
                            "$ref": "#/definitions/models.DeviceAuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/device/poll": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Poll Device Token",
                "parameters": [
                    {
                        "description": "Poll Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DevicePollRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Access Token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Pending/Expired",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get Login History",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Forum User ID",
                        "name": "forum_user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "History",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/pending-ips": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get Pending IPs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Forum User ID",
                        "name": "forum_user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pending IPs",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/pending-ips/mark-notified": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Mark IPs Notified",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MarkNotifiedRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/auth/pending-ips/{id}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Resolve Pending IP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Approval ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Action",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ResolveIPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/smf-verify": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify SMF Token (Legacy)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "GUID",
                        "name": "guid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Player Name",
                        "name": "player_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "server_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Result",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/trusted-ips": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get Trusted IPs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Forum User ID",
                        "name": "forum_user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Trusted IPs",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/trusted-ips/{id}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Remove Trusted IP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IP ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Forum User ID",
                        "name": "forum_user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/verify": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify Game Token",
                "parameters": [
                    {
                        "description": "Verify Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VerifyTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Verification Result",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Pending Approval",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/ingest/events": {
            "post": {
                "security": [
                    {
                        "ServerToken": []
                    }
                ],
                "description": "Accepts newline-separated JSON events from game servers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ingestion"
                ],
                "summary": "Ingest Game Events",
                "parameters": [
                    {
                        "description": "Events",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RawEvent"
                            }
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ingest/match-result": {
            "post": {
                "security": [
                    {
                        "ServerToken": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ingestion"
                ],
                "summary": "Ingest Match Result",
                "parameters": [
                    {
                        "description": "Match Result",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MatchResult"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Processed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers": {
            "get": {
                "description": "List active servers with status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "List All Servers",
                "responses": {
                    "200": {
                        "description": "Server List",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ServerOverview"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/favorites": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Get User Favorites",
                "responses": {
                    "200": {
                        "description": "Favorites",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ServerOverview"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/rankings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Get Server Rankings",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rankings",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ServerOverview"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/register": {
            "post": {
                "description": "Registers a new game server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Register Server",
                "parameters": [
                    {
                        "description": "Server Info",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterServerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Server Credentials",
                        "schema": {
                            "$ref": "#/definitions/models.RegisterServerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/stats": {
            "get": {
                "description": "Aggregate stats across all servers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Global Network Stats",
                "responses": {
                    "200": {
                        "description": "Network Stats",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}": {
            "get": {
                "description": "Detailed server info including lifetime stats",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Server Detail",
                        "schema": {
                            "$ref": "#/definitions/models.ServerOverview"
                        }
                    },
                    "400": {
                        "description": "Missing ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/activity-timeline": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Activity Timeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 7,
                        "description": "Days",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Timeline",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/countries": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Country Stats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Country Data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/favorite": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Check Favorite Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Add Favorite Server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nickname",
                        "name": "nickname",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Remove Favorite Server",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/live": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Get Server Live Status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Live Status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Missing ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/map-rotation": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Map Rotation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "Days",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rotation Data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/maps": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Map Stats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Map Stats",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MapStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/matches": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Recent Matches",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Matches",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MatchResult"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/peak-hours": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Peak Hours Heatmap",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "Days",
                        "name": "days",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Heatmap Data",
                        "schema": {
                            "$ref": "#/definitions/models.PeakHoursHeatmap"
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/player-history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Player History",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 24,
                        "description": "Hours",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "History Data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/players": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Historical Players",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Players List",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/top-players": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Top Players",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Top Players",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.PlayerStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers/{id}/weapons": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Weapon Stats",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Weapon Stats",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WeaponStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats/leaderboard": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leaderboards"
                ],
                "summary": "Get Global Leaderboard",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Leaderboard",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats/matches": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Match"
                ],
                "summary": "Get Recent Matches",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 25,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Matches",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MatchResult"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats/server/activity": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Global Server Activity",
                "responses": {
                    "200": {
                        "description": "Activity Data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats/server/maps": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Global Map Stats",
                "responses": {
                    "200": {
                        "description": "Map Stats",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MapStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats/server/pulse": {
            "get": {
                "description": "Real-time heartbeat of server activity and chaos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Server Pulse (Main)",
                "responses": {
                    "200": {
                        "description": "Pulse Data",
                        "schema": {
                            "$ref": "#/definitions/models.ServerPulse"
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stats/weapons": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Server"
                ],
                "summary": "Get Global Weapon Stats",
                "responses": {
                    "200": {
                        "description": "Weapon Stats",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WeaponStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.DeviceAuthRequest": {
            "type": "object",
            "properties": {
                "device_code": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "interval": {
                    "description": "Polling interval in seconds",
                    "type": "integer"
                },
                "user_code": {
                    "description": "Short code for user to enter",
                    "type": "string"
                },
                "verification_uri": {
                    "description": "URL to visit",
                    "type": "string"
                }
            }
        },
        "models.DeviceAuthResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "description": "ISO8601",
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "is_new": {
                    "type": "boolean"
                },
                "user_code": {
                    "type": "string"
                }
            }
        },
        "models.DevicePollRequest": {
            "type": "object",
            "properties": {
                "device_code": {
                    "type": "string"
                }
            }
        },
        "models.EventType": {
            "type": "string",
            "enum": [
                "game_init",
                "game_start",
                "game_end",
                "match_start",
                "match_end",
                "match_outcome",
                "round_start",
                "round_end",
                "warmup_start",
                "warmup_end",
                "intermission_start",
                "kill",
                "death",
                "damage",
                "player_pain",
                "headshot",
                "player_suicide",
                "player_crushed",
                "player_telefragged",
                "player_roadkill",
                "player_bash",
                "player_teamkill",
                "weapon_fire",
                "weapon_hit",
                "weapon_change",
                "weapon_reload",
                "weapon_reload_done",
                "weapon_ready",
                "weapon_no_ammo",
                "weapon_holster",
                "weapon_raise",
                "weapon_drop",
                "grenade_throw",
                "grenade_explode",
                "jump",
                "land",
                "crouch",
                "prone",
                "player_stand",
                "player_spawn",
                "player_respawn",
                "distance",
                "ladder_mount",
                "ladder_dismount",
                "player_use",
                "player_use_object_start",
                "player_use_object_finish",
                "player_spectate",
                "player_freeze",
                "player_say",
                "item_pickup",
                "item_drop",
                "item_respawn",
                "health_pickup",
                "ammo_pickup",
                "vehicle_enter",
                "vehicle_exit",
                "vehicle_death",
                "vehicle_collision",
                "turret_enter",
                "turret_exit",
                "server_init",
                "server_start",
                "server_shutdown",
                "server_spawned",
                "server_console_command",
                "heartbeat",
                "map_load_start",
                "map_load_end",
                "map_change_start",
                "map_restart",
                "team_join",
                "team_change",
                "vote_start",
                "vote_passed",
                "vote_failed",
                "client_connect",
                "client_disconnect",
                "client_begin",
                "client_userinfo_changed",
                "player_inactivity_drop",
                "door_open",
                "door_close",
                "explosion",
                "actor_spawn",
                "actor_killed",
                "bot_spawn",
                "bot_killed",
                "bot_roam",
                "bot_curious",
                "bot_attack",
                "objective_update",
                "objective_capture",
                "score_change",
                "teamkill_kick",
                "connect",
                "disconnect",
                "spawn",
                "chat",
                "use",
                "reload",
                "team_win",
                "identity_claim"
            ],
            "x-enum-comments": {
                "EventChat": "Alias for player_say",
                "EventConnect": "Alias for client_connect",
                "EventDisconnect": "Alias for client_disconnect",
                "EventIdentityClaim": "Special event (not in 92)",
                "EventReload": "Alias for weapon_reload",
                "EventSpawn": "Alias for player_spawn",
                "EventTeamWin": "Special event (not in 92)",
                "EventUse": "Alias for player_use"
            },
            "x-enum-descriptions": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "Alias for client_connect",
                "Alias for client_disconnect",
                "Alias for player_spawn",
                "Alias for player_say",
                "Alias for player_use",
                "Alias for weapon_reload",
                "Special event (not in 92)",
                "Special event (not in 92)"
            ],
            "x-enum-varnames": [
                "EventGameInit",
                "EventGameStart",
                "EventGameEnd",
                "EventMatchStart",
                "EventMatchEnd",
                "EventMatchOutcome",
                "EventRoundStart",
                "EventRoundEnd",
                "EventWarmupStart",
                "EventWarmupEnd",
                "EventIntermissionStart",
                "EventKill",
                "EventDeath",
                "EventDamage",
                "EventPlayerPain",
                "EventHeadshot",
                "EventPlayerSuicide",
                "EventPlayerCrushed",
                "EventPlayerTelefragged",
                "EventPlayerRoadkill",
                "EventPlayerBash",
                "EventPlayerTeamkill",
                "EventWeaponFire",
                "EventWeaponHit",
                "EventWeaponChange",
                "EventWeaponReload",
                "EventWeaponReloadDone",
                "EventWeaponReady",
                "EventWeaponNoAmmo",
                "EventWeaponHolster",
                "EventWeaponRaise",
                "EventWeaponDrop",
                "EventGrenadeThrow",
                "EventGrenadeExplode",
                "EventJump",
                "EventLand",
                "EventCrouch",
                "EventProne",
                "EventPlayerStand",
                "EventPlayerSpawn",
                "EventPlayerRespawn",
                "EventDistance",
                "EventLadderMount",
                "EventLadderDismount",
                "EventPlayerUse",
                "EventPlayerUseObjectStart",
                "EventPlayerUseObjectFinish",
                "EventPlayerSpectate",
                "EventPlayerFreeze",
                "EventPlayerSay",
                "EventItemPickup",
                "EventItemDrop",
                "EventItemRespawn",
                "EventHealthPickup",
                "EventAmmoPickup",
                "EventVehicleEnter",
                "EventVehicleExit",
                "EventVehicleDeath",
                "EventVehicleCollision",
                "EventTurretEnter",
                "EventTurretExit",
                "EventServerInit",
                "EventServerStart",
                "EventServerShutdown",
                "EventServerSpawned",
                "EventServerConsoleCommand",
                "EventHeartbeat",
                "EventMapLoadStart",
                "EventMapLoadEnd",
                "EventMapChangeStart",
                "EventMapRestart",
                "EventTeamJoin",
                "EventTeamChange",
                "EventVoteStart",
                "EventVotePassed",
                "EventVoteFailed",
                "EventClientConnect",
                "EventClientDisconnect",
                "EventClientBegin",
                "EventClientUserinfoChanged",
                "EventPlayerInactivityDrop",
                "EventDoorOpen",
                "EventDoorClose",
                "EventExplosion",
                "EventActorSpawn",
                "EventActorKilled",
                "EventBotSpawn",
                "EventBotKilled",
                "EventBotRoam",
                "EventBotCurious",
                "EventBotAttack",
                "EventObjectiveUpdate",
                "EventObjectiveCapture",
                "EventScoreChange",
                "EventTeamkillKick",
                "EventConnect",
                "EventDisconnect",
                "EventSpawn",
                "EventChat",
                "EventUse",
                "EventReload",
                "EventTeamWin",
                "EventIdentityClaim"
            ]
        },
        "models.MapStats": {
            "type": "object",
            "properties": {
                "deaths": {
                    "type": "integer"
                },
                "headshots": {
                    "type": "integer"
                },
                "kd_ratio": {
                    "type": "number"
                },
                "kills": {
                    "type": "integer"
                },
                "map_name": {
                    "type": "string"
                },
                "matches_played": {
                    "type": "integer"
                }
            }
        },
        "models.MarkNotifiedRequest": {
            "type": "object",
            "properties": {
                "forum_user_id": {
                    "type": "integer"
                },
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.MatchResult": {
            "type": "object",
            "properties": {
                "allies_score": {
                    "type": "integer"
                },
                "axis_score": {
                    "type": "integer"
                },
                "bracket_match": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "gametype": {
                    "type": "string"
                },
                "map_name": {
                    "type": "string"
                },
                "match_id": {
                    "type": "string"
                },
                "server_id": {
                    "type": "string"
                },
                "total_rounds": {
                    "type": "integer"
                },
                "tournament_id": {
                    "description": "Tournament context (optional)",
                    "type": "string"
                },
                "winning_team": {
                    "type": "string"
                }
            }
        },
        "models.PeakHoursHeatmap": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "[day][hour] = player count",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                },
                "days": {
                    "description": "Mon-Sun",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hours": {
                    "description": "0-23",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "peak": {
                    "$ref": "#/definitions/models.PeakInfo"
                }
            }
        },
        "models.PeakInfo": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "string"
                },
                "hour": {
                    "type": "integer"
                },
                "players": {
                    "type": "integer"
                }
            }
        },
        "models.PlayerStats": {
            "type": "object",
            "properties": {
                "accuracy": {
                    "type": "number"
                },
                "close_range_kills": {
                    "description": "\u003c5m",
                    "type": "integer"
                },
                "collateral_kills": {
                    "type": "integer"
                },
                "crouch_time_seconds": {
                    "type": "number"
                },
                "headshot_percent": {
                    "type": "number"
                },
                "jump_count": {
                    "type": "integer"
                },
                "kd_ratio": {
                    "description": "Computed",
                    "type": "number"
                },
                "kills_per_minute": {
                    "type": "number"
                },
                "kills_while_crouching": {
                    "type": "integer"
                },
                "kills_while_moving": {
                    "type": "integer"
                },
                "kills_while_prone": {
                    "description": "Stance Metrics",
                    "type": "integer"
                },
                "kills_while_standing": {
                    "type": "integer"
                },
                "kills_while_stationary": {
                    "type": "integer"
                },
                "last_active": {
                    "type": "string"
                },
                "long_range_kills": {
                    "description": "Granular Combat Metrics",
                    "type": "integer"
                },
                "matches_played": {
                    "type": "integer"
                },
                "matches_won": {
                    "type": "integer"
                },
                "name": {
                    "description": "Alias for PHP",
                    "type": "string"
                },
                "play_time_seconds": {
                    "type": "number"
                },
                "player_id": {
                    "type": "string"
                },
                "player_name": {
                    "type": "string"
                },
                "prone_time_seconds": {
                    "type": "number"
                },
                "shots_fired": {
                    "type": "integer"
                },
                "shots_hit": {
                    "type": "integer"
                },
                "sprint_distance_km": {
                    "type": "number"
                },
                "total_damage": {
                    "type": "integer"
                },
                "total_deaths": {
                    "type": "integer"
                },
                "total_distance_km": {
                    "description": "Movement Metrics",
                    "type": "number"
                },
                "total_headshots": {
                    "type": "integer"
                },
                "total_kills": {
                    "type": "integer"
                },
                "wallbang_kills": {
                    "type": "integer"
                },
                "win_rate": {
                    "type": "number"
                }
            }
        },
        "models.RawEvent": {
            "type": "object",
            "properties": {
                "aim_pitch": {
                    "description": "Aim angles",
                    "type": "number"
                },
                "aim_yaw": {
                    "type": "number"
                },
                "allies_score": {
                    "type": "integer"
                },
                "ammo_remaining": {
                    "type": "integer"
                },
                "attacker_guid": {
                    "type": "string"
                },
                "attacker_name": {
                    "description": "Attacker info (for kill/damage events)",
                    "type": "string"
                },
                "attacker_pitch": {
                    "type": "number"
                },
                "attacker_smf_id": {
                    "description": "SMF member ID (if authenticated)",
                    "type": "integer"
                },
                "attacker_stance": {
                    "type": "string"
                },
                "attacker_team": {
                    "type": "string"
                },
                "attacker_x": {
                    "type": "number"
                },
                "attacker_y": {
                    "type": "number"
                },
                "attacker_yaw": {
                    "type": "number"
                },
                "attacker_z": {
                    "type": "number"
                },
                "axis_score": {
                    "type": "integer"
                },
                "bot_id": {
                    "type": "string"
                },
                "client_num": {
                    "type": "integer"
                },
                "code": {
                    "description": "Identity claim",
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "damage": {
                    "type": "integer"
                },
                "distance": {
                    "type": "number"
                },
                "driven": {
                    "type": "number"
                },
                "duration": {
                    "type": "number"
                },
                "entity": {
                    "description": "Entity",
                    "type": "string"
                },
                "fall_height": {
                    "description": "Movement",
                    "type": "number"
                },
                "fraglimit": {
                    "type": "string"
                },
                "gametype": {
                    "description": "Match lifecycle",
                    "type": "string"
                },
                "hitloc": {
                    "type": "string"
                },
                "inflictor": {
                    "type": "string"
                },
                "item": {
                    "description": "Items",
                    "type": "string"
                },
                "map_name": {
                    "type": "string"
                },
                "match_id": {
                    "type": "string"
                },
                "match_outcome": {
                    "description": "Match Outcome (1 = Win, 0 = Loss)",
                    "type": "integer"
                },
                "maxclients": {
                    "type": "string"
                },
                "message": {
                    "description": "Chat",
                    "type": "string"
                },
                "new_team": {
                    "type": "string"
                },
                "new_weapon": {
                    "type": "string"
                },
                "objective": {
                    "description": "New Tracker Fields",
                    "type": "string"
                },
                "objective_status": {
                    "type": "string"
                },
                "old_team": {
                    "description": "Team change",
                    "type": "string"
                },
                "old_weapon": {
                    "type": "string"
                },
                "player_count": {
                    "type": "integer"
                },
                "player_guid": {
                    "type": "string"
                },
                "player_name": {
                    "description": "Player info (primary actor for single-player events)",
                    "type": "string"
                },
                "player_smf_id": {
                    "description": "SMF member ID (if authenticated)",
                    "type": "integer"
                },
                "player_stance": {
                    "type": "string"
                },
                "player_team": {
                    "type": "string"
                },
                "pos_x": {
                    "type": "number"
                },
                "pos_y": {
                    "type": "number"
                },
                "pos_z": {
                    "type": "number"
                },
                "projectile": {
                    "type": "string"
                },
                "round_number": {
                    "type": "integer"
                },
                "seat": {
                    "type": "string"
                },
                "server_id": {
                    "type": "string"
                },
                "server_token": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "sprinted": {
                    "type": "number"
                },
                "swam": {
                    "type": "number"
                },
                "target_guid": {
                    "type": "string"
                },
                "target_name": {
                    "description": "Target info (for hits)",
                    "type": "string"
                },
                "target_smf_id": {
                    "description": "SMF member ID (if authenticated)",
                    "type": "integer"
                },
                "target_stance": {
                    "type": "string"
                },
                "timelimit": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "number"
                },
                "total_rounds": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/models.EventType"
                },
                "victim_guid": {
                    "type": "string"
                },
                "victim_name": {
                    "description": "Victim info",
                    "type": "string"
                },
                "victim_smf_id": {
                    "description": "SMF member ID (if authenticated)",
                    "type": "integer"
                },
                "victim_stance": {
                    "type": "string"
                },
                "victim_team": {
                    "type": "string"
                },
                "victim_x": {
                    "type": "number"
                },
                "victim_y": {
                    "type": "number"
                },
                "victim_z": {
                    "type": "number"
                },
                "walked": {
                    "type": "number"
                },
                "weapon": {
                    "description": "Weapon/damage info",
                    "type": "string"
                },
                "winning_team": {
                    "type": "string"
                }
            }
        },
        "models.RegisterServerRequest": {
            "type": "object",
            "properties": {
                "ip_address": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                }
            }
        },
        "models.RegisterServerResponse": {
            "type": "object",
            "properties": {
                "server_id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.ResolveIPRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "\"approve\" or \"deny\"",
                    "type": "string"
                },
                "forum_user_id": {
                    "type": "integer"
                },
                "label": {
                    "description": "Optional label",
                    "type": "string"
                }
            }
        },
        "models.ServerOverview": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avg_players_24h": {
                    "type": "number"
                },
                "country": {
                    "type": "string"
                },
                "current_map": {
                    "type": "string"
                },
                "current_players": {
                    "type": "integer"
                },
                "display_name": {
                    "description": "Name:Port format",
                    "type": "string"
                },
                "gametype": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_online": {
                    "type": "boolean"
                },
                "last_seen": {
                    "type": "string"
                },
                "max_players": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "peak_players_24h": {
                    "type": "integer"
                },
                "port": {
                    "type": "integer"
                },
                "rank": {
                    "description": "Server ranking",
                    "type": "integer"
                },
                "region": {
                    "type": "string"
                },
                "total_kills": {
                    "type": "integer"
                },
                "total_matches": {
                    "type": "integer"
                },
                "unique_players": {
                    "type": "integer"
                },
                "uptime_percent": {
                    "type": "number"
                }
            }
        },
        "models.ServerPulse": {
            "type": "object",
            "properties": {
                "active_players": {
                    "description": "Currently online (approx)",
                    "type": "integer"
                },
                "lead_exchange_rate": {
                    "description": "Estimated lead changes per match",
                    "type": "number"
                },
                "lethality_rating": {
                    "description": "Kills per minute",
                    "type": "number"
                },
                "meat_grinder_map": {
                    "description": "Map with most deaths/minute",
                    "type": "string"
                },
                "total_lead_poured": {
                    "description": "Total bullets hit",
                    "type": "integer"
                }
            }
        },
        "models.VerifyTokenRequest": {
            "type": "object",
            "properties": {
                "player_guid": {
                    "type": "string"
                },
                "player_ip": {
                    "type": "string"
                },
                "server_address": {
                    "type": "string"
                },
                "server_name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.WeaponStats": {
            "type": "object",
            "properties": {
                "accuracy": {
                    "type": "number"
                },
                "damage": {
                    "type": "integer"
                },
                "deaths": {
                    "type": "integer"
                },
                "headshots": {
                    "type": "integer"
                },
                "kills": {
                    "type": "integer"
                },
                "shots_fired": {
                    "type": "integer"
                },
                "shots_hit": {
                    "type": "integer"
                },
                "weapon": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "ServerToken": {
            "type": "apiKey",
            "name": "X-Server-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "api.moh-central.net",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "OpenMOHAA Stats API",
	Description:      "High-throughput competitive statistics and tournament infrastructure for Medal of Honor: Allied Assault.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
