// Code generated by tools/generate_types.py. DO NOT EDIT.
// Generated at: 2026-04-14T17:34:10.657723
// Source: opm-stats-api/web/static/openapi.yaml

package handlers

import "github.com/openmohaa/stats-api/internal/models"

// normalizeEventType maps game script event types to canonical API types.
// This ensures consistent event_type values in ClickHouse for querying.
// GENERATED - edit openapi.yaml and run `make generate-types`
func normalizeEventType(eventType models.EventType) models.EventType {
	switch eventType {
	default:
		return eventType
	}
}
